import type { Metadata } from 'next';
import { Suspense } from 'react';
import './global.css';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/context/ThemeContext';

const expoArabicBold = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Bold.ttf' });
const expoArabicBook = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Book.ttf' });
const expoArabicLight = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Light.ttf' });
const expoArabicMedium = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Medium.ttf' });

export const metadata: Metadata = {
  title: 'Rami',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={'bg-primary text-primary-foreground h-screen'}>
    <Suspense fallback={<div className="">loading...</div>}>
      <ThemeProvider>
        {children}
      </ThemeProvider>
    </Suspense>
    <script
      dangerouslySetInnerHTML={{
        __html: `
              (function() {
                const savedTheme = localStorage.getItem("theme");
                const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

                if (savedTheme === "dark") {
                  document.documentElement.classList.add("dark");
                } else if (savedTheme === "light") {
                  document.documentElement.classList.remove("dark");
                } else {
                  // If "system" or no preference is saved, follow system theme
                  document.documentElement.classList.toggle("dark", prefersDark);
                }
              })();
            `,
      }}
    />
    </body>
    </html>
  );
}
