import type { Metadata } from 'next';
import { Suspense } from 'react';
import './global.css';
import localFont from 'next/font/local';

const expoArabicBold = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Bold.ttf' });
const expoArabicBook = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Book.ttf' });
const expoArabicLight = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Light.ttf' });
const expoArabicMedium = localFont({ src: '../fonts/Expo Arabic/Expo Arabic Medium.ttf' });

export const metadata: Metadata = {
  title: 'Raji',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <head title={'Raji'}>
    </head>
    <body className={'bg-primary text-primary-foreground h-screen'}>
    <Suspense fallback={<div className="">loading...</div>}>
      {children}
    </Suspense>
    <script
      dangerouslySetInnerHTML={{
        __html: `
              document.documentElement.classList.toggle(
                "dark",
                localStorage.theme === "dark" ||
                  (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches),
              );
            `,
      }}
    />
    </body>
    </html>
  );
}
