import type {Metadata} from 'next'
import {Suspense} from 'react'
import './global.css'
import localFont from 'next/font/local'

const expoArabicBold = localFont({src: '../fonts/Expo Arabic/Expo Arabic Bold.ttf'});
const expoArabicBook = localFont({src: '../fonts/Expo Arabic/Expo Arabic Book.ttf'});
const expoArabicLight = localFont({src: '../fonts/Expo Arabic/Expo Arabic Light.ttf'});
const expoArabicMedium = localFont({src: '../fonts/Expo Arabic/Expo Arabic Medium.ttf'});

export const metadata: Metadata = {
    title: 'raji',
    description: 'Generated by create next app'
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang='en'>
        <body>
        <Suspense fallback={<div className=''>loading...</div>}>
            {children}
        </Suspense>
        </body>
        </html>
    )
}
